name: build

on:
  push:
    branches: [master, ci]
  pull_request:
    branches: [master]

env:
  CMAKE_COMMON_ARGS: >-
    -DQ2PRO_ANTICHEAT_SERVER=ON
    -DQ2PRO_USE_AVCODEC=OFF
    -DQ2PRO_CLIENT_GTV=ON
    -DQ2PRO_PACKETDUP_HACK=ON
    -DQ2PRO_TESTS=ON
    -DQ2PRO_VARIABLE_FPS=ON

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [gcc, clang]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build libsdl2-dev libopenal-dev \
          libpng-dev libjpeg-dev zlib1g-dev mesa-common-dev \
          libcurl4-gnutls-dev libx11-dev libxi-dev \
          libwayland-dev wayland-protocols libdecor-0-dev

      - name: Configure
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_C_COMPILER=${{ matrix.cc }} \
            ${{ env.CMAKE_COMMON_ARGS }}

      - name: Build
        run: cmake --build build

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install cmake ninja sdl2 openal-soft libpng jpeg-turbo

      - name: Configure
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DQ2PRO_ICMP_ERRORS=OFF \
            -DQ2PRO_USE_WAYLAND=OFF \
            -DQ2PRO_USE_X11=OFF \
            -DCMAKE_PREFIX_PATH="/opt/homebrew/opt/openal-soft" \
            ${{ env.CMAKE_COMMON_ARGS }}

      - name: Build
        run: cmake --build build

  freebsd:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: cross-platform-actions/action@v0.27.0
        with:
          operating_system: freebsd
          architecture: x86-64
          version: '14.2'
          run: |
            sudo pkg update
            sudo pkg install -y git cmake ninja pkgconf openal-soft \
            sdl2 curl png jpeg-turbo libx11 libdecor evdev-proto wayland-protocols
            cmake -B build -G Ninja \
              -DCMAKE_BUILD_TYPE=Release \
              -DQ2PRO_ICMP_ERRORS=OFF \
              ${{ env.CMAKE_COMMON_ARGS }}
            cmake --build build
